### ISSUE TITLE
addRarityPercentForLayer

### ISSUE THREAD

**Issue by Y-Ali** [HashLips/generative-art-opensource#33]
Hey, so I'm kind of a noob at this... Can someone explain this part of the code please and how I am supposed to adjust the percentages for each layer (and just overall how this part works)?

```
addRarityPercentForLayer('super_rare', 'ball', { 'super_rare': 33, 'rare': 33, 'original': 33 });
addRarityPercentForLayer('super_rare', 'eye color', { 'super_rare': 50, 'rare': 25, 'original': 25 });
addRarityPercentForLayer('original', 'eye color', { 'super_rare': 50, 'rare': 25, 'original': 25 });
```

Thank you!

**Comment by Ponda1** [comment]
You can use this code to refine the generator even more my changing the probability of each layer rarity. For example if you have 2 layers called "background" and "accessories" you can change the code to something like this :

addRarityPercentForLayer('super_rare', 'background', { 'super_rare': 20, 'rare': 30, 'original': 50 });
addRarityPercentForLayer('rare', 'background', { 'super_rare': 10, 'rare': 25, 'original': 65 });
addRarityPercentForLayer('original', 'accessories, { 'super_rare': 50, 'rare': 25, 'original': 25 });

The total of each rarity layer should equal 100. I hope you understood my bad explanation lol

**Comment by Y-Ali** [comment]
Thanks for the reply @Ponda1 !  So what if I have **one** layer called background for example and only **one** .png file in the **super_rare** folder?

I did something like this:

`addRarityPercentForLayer('super_rare', 'iris', { 'super_rare': 20, 'rare': 30, 'original': 50 });`

but it gives this output and error message:

```
creating NFT 1 of 50
- Rarity: original
use random rarity super_rare
- dna: 09-03-04--00
(node:28092) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'path' of undefined
```

**Comment by Ponda1** [comment]
Since you only have one element in "background" and its in the super_rare rarity. You can change the code to this:


addRarityPercentForLayer('super_rare', 'background', { 'super_rare': 100, 'rare': 0, 'original': 0 });
addRarityPercentForLayer('rare', 'background', { 'super_rare': 100, 'rare': 0, 'original': 0});
addRarityPercentForLayer('original', 'background', { 'super_rare': 100, 'rare': 0, 'original': 0 });

There could be a better way of doing this but this is just what I did personally.
I hope this answered your question

**Comment by Y-Ali** [comment]
I'm sure there is but your suggestion has fixed it for now. Thank you @Ponda1 !!!
